theme: jekyll-theme-primer
title: Crime in the USA - Context
description: Analysing data to determine demographic context of crimes
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
